config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books
  resources :csv_files

    #root to: 'books#index'
    root to: 'static_pages#home' #, layout: 'application_login_register'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
     get '/static_pages/home', to: 'static_pages#home', as: 'home_page'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
require 'csv'
class Book < ApplicationRecord
  belongs_to :author
  validates_uniqueness_of :uuid, :allow_blank => true, :allow_nil => true

end

app/models/csv_file.rb
require 'csv'
require 'open-uri'
require 'rest-client'

class CsvFile < ApplicationRecord
  mount_uploader :file, BookUploader
  after_create :import_books
  after_create :api_request
  validate :validate_books
  after_create :save_attr

  def import_books
    ActiveRecord::Base.transaction do
      begin
        csv_text = open(file.url)
        csv = CSV.parse(csv_text, :headers => true)
        csv.each do |row|
          book_hash = Book.new
          book_hash.title = row["Book title"]
          book_hash.author = Author.find_or_create_by(name: row["Book author"])
          book_hash.published_at = Date.parse(row["Date published"])
          book_hash.uuid = row["Unique identifier for the book"]
          book_hash.publisher_name = row["Publisher name"]
          book_hash.user_id = user_id
          book_hash.save!
        end
      rescue => error
        puts error
        raise ActiveRecord::Rollback, error
        puts "Can't open IO device."
      end
    end
  end


  private
  #==========Validating book, with unique UUID=================================================
  def validate_books
    csv_text = open(file.url)
    csv = CSV.parse(csv_text, :headers => true)
        csv.each do |row|
              book_hash = Book.new
              book_hash.title = row["Book title"]
              book_hash.author = Author.find_or_create_by(name: row["Book author"])
              book_hash.published_at = Date.parse(row["Date published"])
              book_hash.uuid = row["Unique identifier for the book"]
              book_hash.publisher_name =  row["Publisher name"]
              book_hash.user_id = user_id
          unless book_hash.valid?
            self.errors[:base] << "UUID Already exist for #{row["Unique identifier for the book"]}"
          end
        end
  end
  #===============================================================================================

  def api_request
    req = RestClient.post 'https://enbrtwpe490a7.x.pipedream.net', {s3_url: file.url}
    puts req
  end

  def save_attr
    self.update_attributes(file_name: file.file.filename, file_url: file.url.to_s)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json

  def index
    @books = Book.where(user_id: current_user.id)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  def create
    @book = Book.new(book_params)
    respond_to do |format|
      @book.user_id = current_user.id
      if @book.save
        format.html { redirect_to books_path, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
      respond_to do |format|
          if @book.update(book_params)
            format.html { redirect_to @book, notice: 'Book was successfully updated.' }
            format.json { render :show, status: :ok, location: @book }
          else
            format.html { render :edit }
            format.json { render json: @book.errors, status: :unprocessable_entity }
          end
      end
  end


  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
      @book.destroy
      respond_to do |format|
        format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
        format.json { head :no_content }
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author_id, :published_at, :uuid, :publisher_name, :user_id)
  end
end

app/controllers/csv_files_controller.rb
class CsvFilesController < ApplicationController
  before_action :set_csv_file, only: [:show, :destroy]

  def index
    @csv_files = CsvFile.where(user_id: current_user.id)
  end

  def show
  end

  def new
    @csv_file = CsvFile.new
  end

  def edit
  end

  def create
    @csv_file = CsvFile.new(cvs_params)
    puts cvs_params.inspect.to_yaml
    respond_to do |format|
      @csv_file.user_id = current_user.id
      if @csv_file.save
        format.html { redirect_to csv_files_path, notice: 'CSV was successfully created.' }
        format.json { render :show, status: :created, location: @csv_file }
      else
        format.html { render :new }
        format.json { render json: @csv_file.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @csv_file.destroy
    respond_to do |format|
      format.html { redirect_to csv_files_url, notice: 'File was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_csv_file
    @csv_file = CsvFile.find(params[:id])
  end

  def cvs_params
    params.require(:csv_file).permit(:file)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    render 'static_pages/home'#,  layout: 'application_login_register'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/csv_files_helper.rb
module CsvFilesHelper
end

app/views/books/_display_books.html.erb
<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Published at</th>
    <th>Uuid</th>
    <th>Publisher name</th>
    <% if defined?(adjust) %>
      <th colspan="3"><div class="text-right"> <%= link_to 'New Book', new_book_path, class: 'btn btn-outline-primary' %> </div></th>
    <%end %>
  </tr>
  </thead>

  <tbody>
  <% books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%=  book.author.try(:name) %></td>
      <td><%= book.published_at %></td>
      <td><%= book.uuid %></td>
      <td><%= book.publisher_name %></td>
      <% if defined?(adjust) %>
      <td><%= link_to 'Show', book %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/books/_form.html.erb
<br>
<br>
<div class="row justify-content-center">
  <div class="col-sm-12 col-md-8">

  <%= form_for(book) do |f| %>
      <div class="card card-fluid">
        <h6 class="card-header">

              <% if defined?(modify_book) %>
                Update <%= book.title %>'s record
              <%elsif defined?(new_book) %>
                Enter new Book's record
              <% end %>
     </h6>

    <div class="card-body" >

      <% if book.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <ul>
            <% book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

          <div class="form-group row">
            <%= f.label :title, class: 'col-form-label col-sm-12 col-md-4' %>
            <div class="col-sm-12 col-md-8">
              <%= f.text_field :title, class: " form-control", placeholder: :title, autofocus: true %>
            </div>
          </div>


            <div class="form-group row">
              <%= f.label :author_id, class: 'col-form-label col-sm-12 col-md-4' %>
              <div class="col-sm-12 col-md-8">
                <%= f.select(:author_id, options_for_select(Author.all.map { |s| [s.name, s.id] }, book.author_id),{prompt: ' -- select -- '}, {class: 'form-control'}) %>
              </div>
            </div>

          <div class="form-group row">
            <%= f.label :published_at, class: 'col-form-label col-sm-12 col-md-4' %>
            <div class="col-sm-12 col-md-8">
              <%= f.datetime_select :published_at, class: " form-control", placeholder: :published_at %>
            </div>
          </div>

          <div class="form-group row">
            <%= f.label :uuid, class: 'col-form-label col-sm-12 col-md-4' %>
            <div class="col-sm-12 col-md-8">
              <%= f.text_field :uuid, class: " form-control", placeholder: :uuid %>
            </div>
          </div>

          <div class="form-group row">
            <%= f.label :publisher_name, class: 'col-form-label col-sm-12 col-md-4' %>
            <div class="col-sm-12 col-md-8">
              <%= f.text_field :publisher_name, class: " form-control", placeholder: :publisher_name %>
            </div>
          </div>
    </div>

          <div class="card-footer text-right">
            <%= link_to 'Back', books_path, class: 'btn btn-primary btn-sm' %> |
            <%= f.submit 'Save', class: 'btn btn-primary btn-sm' %>
          </div>

  <% end %>

    </div>
</div>
</div>

<%= "<div> <br> </div>".html_safe %>

app/views/books/edit.html.erb

<%= render 'books/form', book: @book, modify_book: true %>


app/views/books/index.html.erb
<br>
<br>
<div class="row justify-content-center">
  <div class="col-sm-12 col-md-8">

      <div class="card card-fluid">
          <h6 class="card-header">
            <span class="badge badge-pill badge-info"><h3>Books</h3></span> <br>
            Books Information
          </h6>

          <div class="card-body" >
            <%= render '/books/display_books', books: @books, adjust: true %>
          </div>

          <div class="card-footer text-right">
              <%= link_to 'New Book', new_book_path, class: 'btn btn-outline-primary' %>
          </div>
      </div>

  </div>
</div>

app/views/books/new.html.erb
<%= render 'books/form', book: @book, new_book: true %>

app/views/books/show.html.erb

<br>
<div class="row justify-content-center">
  <div class="col-sm-12 col-md-8">

    <div class="card card-fluid">
          <h6 class="card-header">
              <%= @book.title%>'s details
          </h6>

          <div class="card-body" >
              <%= render 'display_books', books: [@book] %>
          </div>

          <div class="card-footer text-right">
              <%= link_to 'Back', books_path %> |
              <%= link_to 'Edit', edit_book_path(@book) %> |
              <%= link_to 'Destroy', @book, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>

    </div>

  </div>
</div>

app/views/csv_files/_display_csv.html.erb
<!--Partial to display content of the CSV File (in the "Show" and "Index")-->
<table class="table table-bordered table-hover">
  <thead>
      <tr>
        <th>File Name</th>
        <th>Created at</th>
        <th>Updated at</th>
        <th colspan="3"></th>
      </tr>
  </thead>

  <tbody>
    <% csv_files.each do |csv| %>
        <tr>
            <td><%= csv.file.file.filename %></td>
            <td><%= csv.created_at %></td>
            <td><%= csv.updated_at %></td>
            <td><%= link_to 'Show', csv %></td>
            <td><%= link_to 'Destroy', csv, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/csv_files/_form.html.erb
<br>
<br>
<div class="row justify-content-center">
  <div class="col-sm-12 col-md-3">

    <%= form_for(csv_file) do |f| %>
      <div class="card card-fluid">
        <h6 class="card-header">
            Upload CSV File
        </h6>

        <div class="card-body" >
          <%if csv_file.errors.full_messages.any? %>
          <div class="alert alert-danger" role="alert">
            <ul>

          <% csv_file.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
          <%end %>
            </ul>
          </div>
            <%end %>

          <%= f.label :file, "Upload CSV File" %>
          <%= f.file_field :file, class: 'form-control-file', required: true %>

        </div>

        <div class="card-footer text-right">
          <%= link_to 'Back', csv_files_path, class: 'btn btn-primary btn-sm' %> |
          <%= f.submit 'Upload File', class: 'btn btn-primary btn-sm' %>
        </div>

    <% end %>
    </div>
  </div>
</div>
<%= "<div> <br> </div>".html_safe %>

app/views/csv_files/index.html.erb
<br>
<br>
<div class="row justify-content-center">
  <div class="col-sm-12 col-md-8">

    <div class="card card-fluid">
      <h6 class="card-header">
        <span class="badge badge-pill badge-info"><h3>CSV Files</h3></span> <br>
        CSV File Information
      </h6>

      <div class="card-body" >
        <%= render '/csv_files/display_csv', csv_files: @csv_files %>
      </div>

      <div class="card-footer text-right">
        <%= link_to "Upload CSV File", new_csv_file_path, class: 'btn btn-outline-primary'  %> |
        <%= link_to "Home", home_page_path, class: 'btn btn-outline-primary'  %>
      </div>

    </div>
  </div>
</div>

app/views/csv_files/new.html.erb

<%= render 'csv_files/form', csv_file: @csv_file %>

app/views/csv_files/show.html.erb
<!--Show display calling the CSV partial-->
<br>
<div class="row justify-content-center">
  <div class="col-sm-12 col-md-8">

    <div class="card card-fluid">
      <h6 class="card-header">
        CSV File details
      </h6>

      <div class="card-body" >
        <%= render '/csv_files/display_csv', csv_files: [@csv_file] %>

      </div>

      <div class="card-footer text-right">
        <%= link_to 'Back', csv_files_path %> |
        <%= link_to 'Destroy', @csv_file, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Explorer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <!-- <a class="navbar-brand" href="#">Navbar</a> -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item active">
              <a class="nav-link" href="<%=home_page_path%>">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%=books_path %>">Books</a>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=csv_files_path %>">CSV Files</a>
          </li>
        </ul>

  <% if user_signed_in? %>
          <li>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' %> |
          </li>
  <%# else %>
<!--             <li>-->
<!--          <%#= link_to "Login", new_user_session_path, class: 'btn btn-primary btn-sm' %> |-->
<!--           </li>-->
  <% end %>


        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>







    <%= yield %>
  </body>
</html>

app/views/layouts/application_login_register.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ubiquity Book Explorer</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<ul class="hmenu">
  <%= render 'menu/registration_items' %>
  <%= render 'menu/login_items' %>
</ul>

<%= yield %>
</body>
</html>

app/views/menu/_login_items.html.erb
<% if user_signed_in? %>
  <li>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  </li>
<% else %>
  <li>
    <%= link_to('Login', new_user_session_path) %>
  </li>
<% end %>

app/views/menu/_registration_items.html.erb
<% if user_signed_in? %>
  <li>
    <%= link_to('Edit registration', edit_user_registration_path) %>
  </li>
<% else %>
  <li>
    <%= link_to('Register', new_user_registration_path) %>
  </li>
<% end %>

app/views/static_pages/home.html.erb
<h1>Ubiquity Book Explorer!</h1>